### ISSUE TITLE
可以指定转换为某几种格式吗

### ISSUE THREAD

**Issue by techteak** [coder-xiaomo/text-conversion-vscode-extension#1]
比如我其实只需要大驼峰和蛇形 只要能在这两个里面转换就行了
当然 加入原始是小驼峰 也需要能先转为大驼峰 然后再大驼峰和蛇形里面转

**Comment by zhang-brook** [comment]
好建议，我最近添加下这个 VSCode 配置项

**Comment by zhang-brook** [comment]
@techteak 1.1.0版本现已支持通过 VSCode 设置页配置哪些格式是禁用的（配置项: `variable-conversion.disableFormat`），欢迎测试 :smile: 

该配置同时对 QuickPick 菜单转换、右键菜单转换、快捷键循环转换生效

![image](https://github.com/user-attachments/assets/e610a87d-bebf-4878-9f20-b28256e20f60)

-----

By the way, 按我的理解你的描述可能除了禁用某些转换格式外，还有针对目标转换格式排先后顺序的需求。但我暂时没找到合适的 VSCode 的设置页组件，目前不太方便配置，所以暂时没有实现。似乎没有比较合适的配置控件可供使用？（也有可能是支持但是我不知道）

看排序功能是否刚需？如果刚需的话可以另开一个issue。我暂时还没深入研究 VSCode 的配置项，感觉可能需要做个自定义的配置页面进行配置了

**Comment by techteak** [comment]
赞! 我对顺序没有要求 不过设置有点反直觉 是设置屏蔽项

**Comment by zhang-brook** [comment]
> 赞! 我对顺序没有要求 不过设置有点反直觉 是设置屏蔽项

@techteak 😄 哈哈哈，确实是有一点，一开始是准备做成设置启用项的，但这就涉及到一个问题，默认值需要包含所有待转换的目标

因为 VSCode 配置项没办法配置的时候校验，如果这个时候用户配置了一个空数组，那么相当于直接所有转换目标都没了，可能会让用户有些困惑。当然，可以实现为空的时候忽略，这不是技术问题，但配置为空和全部配置上是同样的效果，用户还是会有些许困惑吧

以及，因为 VSCode 他的列表编辑其实不是很方便，假设用户不小心删除一个配置项，但又不知道删除的是哪一项的话，不太好撤回，除非肉眼逐个找一遍，可能体验不太好

另外其实还基于一个考虑，就是后期如果要实现新的转换目标（万一的话，目前暂时没有此计划），但是用户可能修改了一下配置项又改回来，此时配置的默认值已经保存到用户的 settings.json 中了，后面迭代新的格式时用户只能手动改设置项把新引入的转换目标格式加进去，体验可能不太好

如果配置禁用项目的话，初始为空，能够明确用户添加时的配置意图，相对来说不容易误配，如果不小心误配置了，也可以方便的点 x 清除不小心添加的那一项

**Comment by zhang-brook** [comment]
2.1.0 版本已支持使用复选框来配置目标转换格式的开启状态，具体配置如下图，欢迎测试 😄

<img width="945" height="1022" alt="Image" src="https://github.com/user-attachments/assets/47fa0f39-7e2a-4d1c-89dc-baf8325c77f0" />
