### ISSUE TITLE
斜杠转换和箭头转换

### ISSUE THREAD

**Issue by luyuduan** [coder-xiaomo/text-conversion-vscode-extension#3]
斜杠转换就是windows路径是反斜杠的，每次都是替换成斜杠。
箭头转换就是C/C++的成员运算符( . )自动判断替换为( -> ），这个在Qt和VS里有这个功能，很方便，VSCode里还没有
看看有没有想法

**Comment by zhang-brook** [comment]
🤝 多谢建议 

路径的斜杠转换是比较常用的需求，这个功能我近期抽空加上。

不过 C/C++ 我不是太熟悉，你说的( . )替换为(->)具体是怎样的需求呢，就是类似选中范围的( . )全部替换为(->)吗，还是说有些其他的处理逻辑呢？

**Comment by luyuduan** [comment]
箭头转换涉及到语法和静态代码分析，这俩操作符都是用于访问成员的，
变量和引用  用成员访问符（.）来访问其指向对象的成员，这个最常见了
指针  用间接访问符（->）来访问对象的成员。
VS没用过这个功能，但是QT里是这样表现的，
我只用输入（.），后面输入成员符号名，这个（.）就会根据前面的变量类型（指针/其他），自动转换为相应的（.）或者（->）。
![PixPin_2024-11-29_16-34-45](https://github.com/user-attachments/assets/fbf2423b-da22-4a6f-84bc-b1af6ee5b2e0)

**Comment by luyuduan** [comment]
这个功能不用做了，VSCode已经自带了，我没注意，一直都是自己输入的。

**Comment by luyuduan** [comment]
这个箭头转换的功能不用做了，VSCode已经自带。我之前没注意，一直都是自己输入的，刚试了一下，确实已经有了，不好意思。

**Comment by zhang-brook** [comment]
抱歉久等了，路径转换功能目前已经在 [v2.0.0](https://github.com/coder-xiaomo/variable-conversion-vscode-extension/releases/tag/2.0.0) 版本加上了，目前支持 Windows 风格 与 Unix 风格的互转，

插件发布审核需要约半小时，稍后就可以在应用商店更新了

![image](https://github.com/user-attachments/assets/87bf3c09-b820-44cd-a612-8e9e363aa36a)
